Repository SarthakKeshari/Java-Questions-and-Solutions, pull requests merged in 2021-10, with the labels that each got.

#48 add PrimeGame class
  CodeChef/PrimeGame.java
Labels: Level 3, hacktoberfest-accepted

#45 Binary Search Tree in java
  Data Structure/Trees/Binary Trees/BinarySearchTree.java
Labels: Level 3

#49 sorting in java
  Basic Codes/sort.java
Labels: Level 1

#22 factorial-by-loops.java added
  Basic Codes/factorial-by-loops.java
Labels: Level 0

#58 maximum length of sub-array
  Arrays/1D Arrays/maxLength_Of_Subarray.java
Labels: Level 2, hacktoberfest-accepted

#64 Print Binary of number using Bit Manip
  Bit Manipulation/PrintBinary.java
Labels: Level 3, hacktoberfest

#70 maximum freq character
  String Handling/Max_Freq_Character.java
Labels: Level 1, hacktoberfest-accepted

#63 semisort1 problem
  Sorting/semisort1.java
Labels: Level 2, hacktoberfest-accepted

#75 Solution for Keprekar Number
  .vscode/settings.json
  Number Theory/KeprekarNo.java
Labels: Level 2, hacktoberfest-accepted

#81 Added Chef in Vaccination Queue(JAVA)
  CodeChef/vaccination_queue.java
Labels: Level 2, hacktoberfest-accepted

#55 CodeChef Solution for MagicalDoors
  CodeChef/MagicalDoors.java
Labels: Level 3, hacktoberfest-accepted

#84 Duplicate Number
  LeetCode/DuplicateNumber.java
Labels: Level 2, hacktoberfest-accepted

#94 Solution to check a number for palindrome prime
  Number Theory/PrimePal.java
Labels: Level 0

#83 Javelin Qualification
  CodeChef/JavelinQualification.java
Labels: Level 2, hacktoberfest-accepted

#89 Solution to find Minimum and Maximum of an Array
  Recursion/MinMaxRecursion.java
Labels: Level 3, hacktoberfest-accepted

#99 Diagonal
  GeeksForGeeks/diagonal.java
  GeeksForGeeks/welcome.txt
Labels: Level 2, hacktoberfest-accepted

#103 Vedansh123
  Number Theory/Emirp.java
Labels: Level 2, hacktoberfest-accepted

#91 Cyclic sort solution is added
  Sorting/CyclicSort.java
Labels: Level 3, hacktoberfest-accepted

#104 minimum jumps
  GeeksForGeeks/minimum_Jumps.java
Labels: Level 2, hacktoberfest-accepted

#105 Fibonacci series using recursion (solution)
  Recursion/FibonacciSeries.java
Labels: Level 1, hacktoberfest-accepted

#109 Create Binary Tree Maximum Path Sum
  LeetCode/Binary Tree Maximum Path Sum
Labels: Level 3, hacktoberfest-accepted

#88 Create Rotate_Array.java
  LeetCode/Rotate_Array.java
Labels: Level 3, hacktoberfest-accepted

#96 Delete a node from linked list
  LeetCode/DeleteNode.java
Labels: Level 2, hacktoberfest-accepted

#114 Count_text_word
  GeeksForGeeks/CountText.java
Labels: Level 2, hacktoberfest-accepted

#132 Create Search2DMatrix.java
  LeetCode/Search2DMatrix.java
Labels: Level 2, hacktoberfest-accepted

#128 "quick sort in java"
  Sorting/quickSort.java
Labels: Level 3, hacktoberfest-accepted

#129 matrix Multiplication in java
  Arrays/2D Arrays/matrix_Multiplication.java
Labels: Level 2, hacktoberfest-accepted

#153 Make it Divisible (Java)
  CodeChef/MakeitDivisible.java
Labels: Level 2, hacktoberfest-accepted

#151 Java solution for Container with most water
  LeetCode/Container With Most Water.java
Labels: Level 2, hacktoberfest-accepted

#142 Shuffling Parities (java)
  CodeChef/Shuffling_Parties.java
Labels: Level 2, hacktoberfest-accepted

#150 Create NextGreaterElement.java
  LeetCode/NextGreaterElement.java
Labels: Level 2, hacktoberfest-accepted

#158 1828. Queries on Number of Points Inside a Circle
  LeetCode/PointInsideCircle.java
Labels: Level 3, hacktoberfest-accepted

#157 "merge sort in java"
  Sorting/merge-Sort.java
Labels: Level 3, hacktoberfest-accepted

#156 Selection sort in java
  Sorting/selection_Sort.java
Labels: Level 3, hacktoberfest-accepted

#160 Added Java Solution for First missing positive
  LeetCode/First Missing Positive.java
Labels: Level 3, hacktoberfest

#101 search in Infinite Array Added
  GeeksForGeeks/SearchInInfiniteSortedArray.java
Labels: Level 2, hacktoberfest-accepted

#113 IsNthBitSet code added
  Bit Manipulation/IsNthBitSet.java
Labels: Level 2, hacktoberfest-accepted

#143 Intersection of two arrays
  Arrays/1D Arrays/intersectionOfTwoArrays.java
Labels: Level 2, hacktoberfest-accepted

#162 Solution Linear Search
  Searching/LinearSearchJava.java
Labels: Level 2, hacktoberfest-accepted

#165 Solution Matrix Addition
  Arrays/2D Arrays/matrixAddition.java
Labels: Level 2, hacktoberfest-accepted

#167 Median of sorted arrays
  LeetCode/MedianOfTwoSortedArrays-BinarySearch.java
Labels: Level 3, hacktoberfest-accepted

#59 Palindrome
  String Handling/stringPalindrome.java
Labels: Level 1

#170 Generic Stack class added
  Data Structure/Stack/GenericStack.java
Labels: Level 3, hacktoberfest-accepted

#184 Find all duplicates in an array(solved)
  LeetCode/FindAllDuplicatesinanArray.java
Labels: Level 2, hacktoberfest-accepted

#177 Count 1's bit
  LeetCode/count1s.java
Labels: Level 1

#127 Java Exception Handling(Try Catch) [hackerrank]
  Hackerrank/java_exception_handling(try-catch).java
Labels: Level 1, hacktoberfest-accepted

#175 Custom MinHeap and MaxHeap Implementation added
  Data Structure/Heap/CustomMaxHeap.java
  Data Structure/Heap/CustomMinHeap.java
Labels: Level 3, hacktoberfest-accepted

#192 Binary Search
  Searching/binarysearch.java
Labels: Level 2, hacktoberfest-accepted

#173 Create MergeKSortedLists.java
  LeetCode/MergeKSortedLists.java
Labels: Level 3, hacktoberfest-accepted

#196 Solution of Semisorted array
  .vscode/settings.json
  Sorting/import java.util.Scanner;.java
Labels: Level 3, hacktoberfest-accepted

#194 solution of All missing number added
  LeetCode/AllMissingNumber.java
Labels: Level 1

#198 Added NQueens Leetcode Solution
  LeetCode/NQueens.java
Labels: Level 3, hacktoberfest

#197 Insertion Sort
  Sorting/InsertionSort.java
Labels: Level 3, hacktoberfest-accepted

#203 Implement RegEx Date Validation
  String Handling/DateValidation.java
Labels: Level 2, hacktoberfest-accepted

#186 inversions count
  GeeksForGeeks/Inversion_Count.java
Labels: Level 2, hacktoberfest-accepted

#202 Implement Strassen Algorithm
  Arrays/2D Arrays/StrassenAlgorithm.java
Labels: Level 2, hacktoberfest

#174 Armstrong number added
  Number Theory/ArmstrongNumber.java
Labels: Level 2, hacktoberfest

#181 Solution of finding first and last occurrence of number
  LeetCode/Occurrence.java
Labels: Level 2, hacktoberfest-accepted

#180 Modular Exponentiation code added
  Number Theory/ModularExp.java
Labels: Level 2, hacktoberfest-accepted

#206 Testing permutation
  Number Theory/nextpermutation.java
Labels: Level 2, hacktoberfest-accepted

#190 Create insertion_sort.java
  Sorting/insertion_sort.java
Labels: Level 2, hacktoberfest-accepted

#211 Fascinating Number or not
  Number Theory/Fascno.java
Labels: Level 2, hacktoberfest-accepted

#217 CheckOddEven using BitManip code added
  Bit Manipulation/CheckOddEven.java
Labels: Level 2, hacktoberfest-accepted

#219 Unique Binary String
  LeetCode/uniqueBString.java
Labels: Level 2, hacktoberfest-accepted

#216 Java Abstract Class [Hackerrank]
  Java_abstract_class[Hackerrank].java
Labels: Level 1

#226 replacepi
  GeeksForGeeks/replacepi.java
Labels: Level 1

#214 Create Bubble Sort.java
  Sorting/Bubble Sort.java
Labels: Level 2, hacktoberfest-accepted

#230 [ISSUE-227] add program for finding longest palindromic substring
  LeetCode/LongestPalindromicSubstring.java
Labels: Level 2, hacktoberfest-accepted

#223 Solution of finding target number in rotated sorted array
  LeetCode/FindNumber.java
Labels: Level 2, hacktoberfest-accepted

#233 Pow(x,n)
  LeetCode/Pow.java
Labels: Level 1, hacktoberfest-accepted

#215 string search
  Searching/stringsearch.java
Labels: Level 1

#238 Solved LRU_Cache.java
  LeetCode/LRU_Cache.java
Labels: Level 2, hacktoberfest-accepted

#248 Searching element in an array within given range
  Searching/searchinrange.java
Labels: Level 2, hacktoberfest-accepted

#249 Burst_Balloon.java
  LeetCode/Burst_Balloon.java
Labels: Level 3, hacktoberfest-accepted

#251 Create Sort colors.java
  LeetCode/Sort colors.java
Labels: Level 3, hacktoberfest-accepted

#252 Rotate a Matrix by 90deg added
  GeeksForGeeks/Rotate_Matrix_by_90deg.java
Labels: Level 2, hacktoberfest-accepted

#254 [ISSUE-250]add a solution for Predict the winner problem
  LeetCode/PredictTheWinner.java
Labels: Level 3, hacktoberfest-accepted

#260 Create BasicQueue.java
  Data Structure/Queue/Basic Queue/BasicQueue.java
Labels: Level 2, hacktoberfest-accepted

#265 End_of_file_solution.java
  Hackerrank/End_of_file_solution.java
Labels: Level 1

#261 Create Reorder_List.java
  LeetCode/Reorder_List.java
Labels: Level 2, hacktoberfest-accepted

#266 🌟Website name declaration
  website_name.txt
Labels: Level 2, hacktoberfest-accepted
