Repository SarthakKeshari/Java-Questions-and-Solutions, pull requests merged in 2021-09, with the labels that each got.

#18 Added solution for positive and negative number
  Basic Codes/Positive_Negative.java
  Basic Codes/multiple_of_two.java
Labels: Level 0

#21 Solution greater than 100
  Basic Codes/Greaterno.java
Labels: Level 0

#27 Added factorial program using recursion
  Basic Codes/Factorial.java
Labels: Level 1

#33 Create birthday.java
  Hackerrank/birthday.java
Labels: Level 2

#39 Root of quadratic
  Basic Codes/RootsOfQuadraticEqn.java
Labels: Level 0
